### ISSUE TITLE
ключ лучше спрятать

### ISSUE THREAD

**Issue by anton-belousov** [nbusko/event_finder_gpt#1]
https://github.com/nbusko/event_finder_gpt/blob/3193f831cd7e611b95a7e7331682aa3aee3a2e02/app/AImanager.py#L11

можно указывать ключи через environment variables при запуске проекта

**Comment by nbusko** [comment]
Спасибо за ревью! теперь ключа там нет
Было бы славно, если бы ты удалил issue, чтобы ключ тут не светить
